[package]
name = "merkletree"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = "0.5"
ark-serialize = "0.5"
ark-bls12-381 = "0.5"  # EC BLS12-381 
ark-ff = "0.5.0"
sha2 = "0.10"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "merkle_tree_benchmarks"
harness = false
